stages:
  - build
  - style
  - test
  - deploy

build-job:
  stage: build
  tags:
    - build
  script:
    - make -C src/cat
    - make -C src/grep
  after_script:
    - cd src
    - chmod +x notification.sh
    - bash notification.sh
  artifacts:
    paths:
    - src/cat/s21_cat
    - src/grep/s21_grep
    expire_in: 30 days
  only:
    - develop

style-job:
  stage: style
  tags:
    - style
  script:
    - clang-format -style=Google -Werror -n src/cat/s21_cat.* src/grep/s21_grep.*
  after_script:
    - cd src
    - chmod +x notification.sh
    - bash notification.sh
  only:
    - develop

test-job:
  stage: test
  tags:
    - test
  when: on_success
  script:
    - cd src
    - bash test.sh
  after_script:
    - cd src
    - chmod +x notification.sh
    - bash notification.sh
  only:
    - develop

deploy-job:
  stage: deploy
  tags:
    - deploy
  needs:
    - build-job
    - style-job
    - test-job
  when: manual
  script:
    - cd src
    - bash deploy.sh
  after_script:
    - cd src
    - chmod +x notification.sh
    - bash notification.sh
  only:
    - develop